// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'RaspberryPi4.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RaspberryPi4 _$RaspberryPi4FromJson(Map<String, dynamic> json) {
  return RaspberryPi4(
    json['id'] as String,
    Board.fromJson(json['board'] as Map<String, dynamic>),
    Pin.fromJson(json['pin1'] as Map<String, dynamic>),
    Pin.fromJson(json['pin2'] as Map<String, dynamic>),
    Pin.fromJson(json['pin3'] as Map<String, dynamic>),
    Pin.fromJson(json['pin4'] as Map<String, dynamic>),
    Pin.fromJson(json['pin5'] as Map<String, dynamic>),
    Pin.fromJson(json['pin6'] as Map<String, dynamic>),
    Pin.fromJson(json['pin7'] as Map<String, dynamic>),
    Pin.fromJson(json['pin8'] as Map<String, dynamic>),
    Pin.fromJson(json['pin9'] as Map<String, dynamic>),
    Pin.fromJson(json['pin10'] as Map<String, dynamic>),
    Pin.fromJson(json['pin11'] as Map<String, dynamic>),
    Pin.fromJson(json['pin12'] as Map<String, dynamic>),
    Pin.fromJson(json['pin13'] as Map<String, dynamic>),
    Pin.fromJson(json['pin14'] as Map<String, dynamic>),
    Pin.fromJson(json['pin15'] as Map<String, dynamic>),
    Pin.fromJson(json['pin16'] as Map<String, dynamic>),
    Pin.fromJson(json['pin17'] as Map<String, dynamic>),
    Pin.fromJson(json['pin18'] as Map<String, dynamic>),
    Pin.fromJson(json['pin19'] as Map<String, dynamic>),
    Pin.fromJson(json['pin20'] as Map<String, dynamic>),
    Pin.fromJson(json['pin21'] as Map<String, dynamic>),
    Pin.fromJson(json['pin22'] as Map<String, dynamic>),
    Pin.fromJson(json['pin23'] as Map<String, dynamic>),
    Pin.fromJson(json['pin24'] as Map<String, dynamic>),
    Pin.fromJson(json['pin25'] as Map<String, dynamic>),
    Pin.fromJson(json['pin26'] as Map<String, dynamic>),
    Pin.fromJson(json['pin27'] as Map<String, dynamic>),
    Pin.fromJson(json['pin28'] as Map<String, dynamic>),
    Pin.fromJson(json['pin29'] as Map<String, dynamic>),
    Pin.fromJson(json['pin30'] as Map<String, dynamic>),
    Pin.fromJson(json['pin31'] as Map<String, dynamic>),
    Pin.fromJson(json['pin32'] as Map<String, dynamic>),
    Pin.fromJson(json['pin33'] as Map<String, dynamic>),
    Pin.fromJson(json['pin34'] as Map<String, dynamic>),
    Pin.fromJson(json['pin35'] as Map<String, dynamic>),
    Pin.fromJson(json['pin36'] as Map<String, dynamic>),
    Pin.fromJson(json['pin37'] as Map<String, dynamic>),
    Pin.fromJson(json['pin38'] as Map<String, dynamic>),
    Pin.fromJson(json['pin39'] as Map<String, dynamic>),
    Pin.fromJson(json['pin40'] as Map<String, dynamic>),
  );
}

Map<String, dynamic> _$RaspberryPi4ToJson(RaspberryPi4 instance) =>
    <String, dynamic>{
      'id': instance.id,
      'board': instance.board,
      'pin1': instance.pin1,
      'pin2': instance.pin2,
      'pin3': instance.pin3,
      'pin4': instance.pin4,
      'pin5': instance.pin5,
      'pin6': instance.pin6,
      'pin7': instance.pin7,
      'pin8': instance.pin8,
      'pin9': instance.pin9,
      'pin10': instance.pin10,
      'pin11': instance.pin11,
      'pin12': instance.pin12,
      'pin13': instance.pin13,
      'pin14': instance.pin14,
      'pin15': instance.pin15,
      'pin16': instance.pin16,
      'pin17': instance.pin17,
      'pin18': instance.pin18,
      'pin19': instance.pin19,
      'pin20': instance.pin20,
      'pin21': instance.pin21,
      'pin22': instance.pin22,
      'pin23': instance.pin23,
      'pin24': instance.pin24,
      'pin25': instance.pin25,
      'pin26': instance.pin26,
      'pin27': instance.pin27,
      'pin28': instance.pin28,
      'pin29': instance.pin29,
      'pin30': instance.pin30,
      'pin31': instance.pin31,
      'pin32': instance.pin32,
      'pin33': instance.pin33,
      'pin34': instance.pin34,
      'pin35': instance.pin35,
      'pin36': instance.pin36,
      'pin37': instance.pin37,
      'pin38': instance.pin38,
      'pin39': instance.pin39,
      'pin40': instance.pin40,
    };
